export const STATIC_DATA = [
  {
    id: 'bitcoin',
    symbol: 'btc',
    name: 'Bitcoin',
    price: '',
    transactions: [
      {
        id: '1',
        price: 26123,
        quantity: 0.002,
        date: '12/5/2023',
        fees: '0.15',
        notes: 'Notes',
        buy: true,
        avgNetCost: 0,
      },
      {
        id: '2',
        price: 27456,
        quantity: 0.003,
        date: '12/5/2023',
        fees: '0.78',
        notes: 'some notes',
        buy: true,
        avgNetCost: 0,
      },
      {
        id: '3',
        price: 26854,
        quantity: -0.001,
        date: '12/5/2019',
        fees: '0.34',
        notes: 'Notes',
        buy: false,
        avgNetCost: 0,
      },
      {
        id: '4',
        price: 28753,
        quantity: 0.003,
        date: '12/6/2023',
        fees: '0.15',
        notes: 'Notes',
        buy: true,
        avgNetCost: 0,
      },
    ],
  },
  {
    id: 'ethereum',
    symbol: 'eth',
    name: 'Ethereum',
    price: '',
    transactions: [
      {
        id: '1',
        price: 1340,
        quantity: 0.01,
        date: '12/5/2023',
        fees: '0.15',
        notes: 'Notes',
        buy: true,
        avgNetCost: 0,
      },
      {
        id: '2',
        price: 1445,
        quantity: 0.022,
        date: '12/5/2023',
        fees: '0.78',
        notes: 'Notes',
        buy: true,
        avgNetCost: 0,
      },
      {
        id: '3',
        price: 1425,
        quantity: -0.02,
        date: '12/5/2019',
        fees: '0.34',
        notes: 'Notes',
        buy: false,
        avgNetCost: 0,
      },
      {
        id: '4',
        price: 1500,
        quantity: 0.465,
        date: '12/6/2023',
        fees: '0.15',
        notes: 'Notes',
        buy: true,
        avgNetCost: 0,
      },
    ],
  },
];
